version: "3"

services:
  node:
    image: node:16
    container_name: harry-potter
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      
  database:
    image: mysql:5.7
    container_name: mysql_harry_potter
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - ./data/seeder:/docker-entrypoint-initdb.d


networks:
  default:
    name: harry-potter_net
