version: "3"

services:
  node:
    image: node:16
    container_name: bug-hunting-harry-potter
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    environment:
      - PORT=3001

networks:
  default:
    name: bug_hunting_net
